//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace winui_project {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.13.0.0")]
    internal sealed partial class logClassificationSettings : global::System.Configuration.ApplicationSettingsBase {
        
        private static logClassificationSettings defaultInstance = ((logClassificationSettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new logClassificationSettings())));
        
        public static logClassificationSettings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string previousFilePath {
            get {
                return ((string)(this["previousFilePath"]));
            }
            set {
                this["previousFilePath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string previousSavePath {
            get {
                return ((string)(this["previousSavePath"]));
            }
            set {
                this["previousSavePath"] = value;
            }
        }
    }
}
